subtask(WORK-230): table actions changes
storyblok/storyblok-design-system pull request #145
Opened 2022-03-04 02:13 UTC by gustavomelki

## Pull request type

Jira Link: [WORK-230](https://storyblok.atlassian.net/browse/WORK-230)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

Go to SbDataTable > Actions Menu, sets a number into hideLabelActionsBreakpoint property, select a row into table and resize the window until hide the action buttons label.

## What is the new behavior?

- Now we have a new property on SbDataTable: hideLabelActionsBreakpoint
- If the window is smaller than the value set, hides the action buttons label and adds a tooltip to the button (on hover)
- Button 'Cancel' now is 'Clear' (and changed to left side)
- Emits the selected rows

## Other information

2022-03-04 12:23 UTC, ademarCardoso approved these changes

2022-03-04 13:06 UTC, thiagosaife requested changes
I changed some parameters and sometimes it works, sometimes don't.

2022-03-04 13:08 UTC, thiagosaife commented
As show [here](https://www.awesomescreenshot.com/video/7721523).

2022-03-07 21:16 UTC, thiagosaife approved these changes

2022-03-07 21:16 UTC, merged