fix(str-974): One line minibrowser slugs
storyblok/storyblok-design-system pull request #231
Opened 2022-06-07 21:45 UTC by anthonysousa

## Pull request type

Jira Link: [STR-974](https://storyblok.atlassian.net/browse/STR-974)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR
To test this PR open the storyfront app and checkout to the branch `bugfix/str-942 `.
1. In the `Content` tab of a Space create a folder or a Story with a very long slug
2. Open any Story and click on the arrow to open the `Content Browser`
3.  The slug should be displayed with an ellipsis `...` at the end if it is too big.

## What is the new behavior?

- This is a small fix for the PR in storyfront https://github.com/storyblok/storyfront/pull/1910. This PR prevent the slug to have linebreaks or scroll bars when the slugs are too long.

| Before                                                                                                        | After                                                                                                         |
|---------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/692423/172488045-b41ecca9-9110-4cd0-847e-b09fdeab6325.png) | ![image](https://user-images.githubusercontent.com/692423/172487989-ca443739-2e83-4616-8671-1f3a2eaf8432.png) |

## Other information

2022-06-07 22:14 UTC, ademarCardoso approved these changes

2022-06-08 12:28 UTC, fernandacanto requested changes
Hi @anthonysousa, how can I test your change in blok.ink? Why I added large texts in the items and even then there was no ellipsis at the end, maybe I'm testing wrong.☺️

2022-06-08 16:33 UTC, fariacc commented
Yeah @anthonysousa, @fernandacanto is right. You should maybe add a new story for the component's storybook. This is a public repository, so everyone should be able to see how such changes work.

2022-06-08 16:34 UTC, fariacc requested changes
Yeah @anthonysousa, @fernandacanto is right. You should maybe add a new story for the component's storybook. This is a public repository, so everyone should be able to see how such changes work.

2022-06-08 20:27 UTC, ademarCardoso commented
@fernandacanto i recorded a video with the example to test:

https://user-images.githubusercontent.com/40925579/172710631-712a773a-82c2-4297-bca7-0f893c6f2885.mov

2022-06-08 20:39 UTC, fernandacanto reviewed
Thanks @ademarCardoso, Its work, but we need the example in storybook. 🙃

2022-06-08 21:52 UTC, ademarCardoso commented
I agree @fernandacanto

2022-06-09 22:01 UTC, fariacc commented
@ademarCardoso @fernandacanto do you guys think that @anthonysousa needs to add the story for this case? I'm just waiting on this to approve.

2022-06-10 10:20 UTC, anthonysousa commented
@fariacc I'm working on the story. I'll commit soon.

2022-06-10 18:44 UTC, fernandacanto approved these changes

2022-06-10 19:15 UTC, fariacc approved these changes

2022-06-10 19:17 UTC, merged