Fix/sb tabs padding
storyblok/storyblok-design-system pull request #235
Opened 2022-06-13 12:39 UTC by lisilinhart

## Pull request type

Jira Link: -

Nikola requested to change the padding in the DS to the following:
![image](https://user-images.githubusercontent.com/11278408/167392429-2757c158-7545-4d1e-aa78-2c991407c12b.png)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

It's good to test inside the storyfront. There will be a second PR in the storyfront to fix all the tabs to be the same and aligned well:

1. `cd storyblok-design-system && git checkout fix/sb-tabs-padding`
2. Then on the localhost navigate the application and check if everything looks correct where tabs are used
3. You can also compare https://storyblok-design-system-git-fix-sb-tabs-padding-storyblok-com.vercel.app/ and https://blok.ink/

https://user-images.githubusercontent.com/11278408/167393508-c9c4ed2e-3f0f-4fef-8c17-aaa8b948ce02.mov

## What is the new behavior?

-  Less padding left and right on sb tabs
- 
- 

## Other information

2022-06-27 08:09 UTC, lisilinhart commented
After talking with Nikola, I still think we can add this change to the DS

2022-06-27 18:29 UTC, fernandacanto commented on src/components/Tabs/tabs.scss
>  }
Hi Lisi, we need this style for when the **isDisabled** property is passed in SbTab.

2022-06-27 19:55 UTC, fariacc requested changes
I still stand with the same comment I made on a previous PR regarding that this doesn't look very good when the tab has icons:

<img width="282" alt="Captura de Tela 2022-06-27 às 16 39 57" src="https://user-images.githubusercontent.com/26799272/176022687-36e229cd-da09-4278-ae8d-56435cc8d064.png">

Besides, these changes introduce some issues when navigating with the tabs buttons. In production it's possible to reach the last tab but on localhost + the DS branch checked out it works differently:

https://user-images.githubusercontent.com/26799272/176022779-460bbaa5-9866-49a0-9e43-409edd9e7d0f.mov

2022-06-29 07:27 UTC, lisilinhart commented
Thanks @fernandacanto @fariacc I will check about these issues

2022-07-05 10:48 UTC, FidalgoMonica approved these changes
Tested together with this https://github.com/storyblok/storyfront/pull/2085 and seems good!

2022-07-05 11:37 UTC, fernandacanto approved these changes
Good job!

2022-07-05 18:11 UTC, merged