bugfix(INT-439): slideover title overlap icon
storyblok/storyblok-design-system pull request #242
Opened 2022-06-27 19:25 UTC by fernandacanto

This PR is required so that the sbSlideover title does not overlap the close icon.

## Pull request type

Jira Link: [INT-439 - [DS] - In SbSlideover the title and X to close overlap](https://storyblok.atlassian.net/browse/INT-439)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR
Go in:
https://storyblok-design-system-dgyoiptsl-storyblok-com.vercel.app/?path=/story/design-system-components-sbslideover--default
Set a new big title.

2022-06-27 22:14 UTC, fariacc requested changes

2022-06-27 22:14 UTC, fariacc commented on src/components/Slideover/slideover.scss
> +    word-break: break-all;
Hey, I have some css suggestions for this.
```
.sb-modal-header__title {   
    word-break: break-word; // so we don't break words into characters
    width: calc(100% - 36px); // which is the width of the close icon
    line-height: 36px; // the space between every line of the title is too big so setting to 36px is the same amount of the icon's height
}
```

Also change `.sb-slideover__close-button` top from 23px to 20px. What do you think?

2022-07-01 12:32 UTC, lisilinhart requested changes
<img width="660" alt="grafik" src="https://user-images.githubusercontent.com/11278408/176894296-19d67f11-e3dc-481c-9bc7-62b39f9155b4.png">

It doesn't work when the word is too long (in firefox), then it's still overlapping. I also think the line-height is a bit too big and maybe it should be cut after two lines?

2022-07-01 14:36 UTC, fernandacanto commented
> 

Hey @lisilinhart, about your questions:

- About not working in Firefox, here it worked, I asked @carlosricciardi-storyblok  to test it too.

- About the height-line, I decreased it a little, I put 30px. 

- About cutting the title, I don't think we should cut it, because that's the title, the user shouldn't be deprived of a title.

2022-07-04 16:50 UTC, thiagosaife approved these changes
Worked pretty well in FireFox, Chrome and Brave.

2022-07-05 18:10 UTC, merged