bugfix(STR-1082): SbDropArea: Problems on drag and drop
storyblok/storyblok-design-system pull request #260
Opened 2022-07-20 04:06 UTC by anthonysousa

This commit improves the `dragleave` event by adding the `pointer-events: none;` to all elements on mouseover.
It also fixes problems with the content size

## Pull request type

Jira Link: [STR-1082](https://storyblok.atlassian.net/browse/STR-1082)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR
Set a small window in the browser (width: 768 px)

1. Open the sbDropArea page
2. From your file system explorer, select a file and drag it to the Asset area (don’t drop it)
4. Drag the Asset out of the window
5. The overlay should disappear.
6. Reload SbDropArea page
7. Again, from your file system explorer, select a file and drag it to the Asset area, don’t drop it, and press the Escape key (Esc)
8. The overlay should disappear.

## What is the new behavior?

- This PR improves the `dragleave` behavior of the SbDropArea and also enhances the CSS for smaller screens

2022-07-20 07:42 UTC, lisilinhart requested changes

2022-07-20 14:58 UTC, emanuelgsouza approved these changes
Besides the comment from @lisilinhart, it seems fine! Nice work

2022-07-20 18:15 UTC, anthonysousa commented on src/components/DropArea/drop-area.scss
> +    * {
@lisilinhart I tried just adding the `pointer-events: none;` to the parent but was not working.
So added it to the `.sb-drop-area__content` when the user is dragging a file to it.

2022-07-22 12:45 UTC, lisilinhart approved these changes

2022-07-22 12:46 UTC, merged