fix(on-270): align collapse icon with my account
storyblok/storyblok-design-system pull request #273
Opened 2022-07-28 10:31 UTC by FidalgoMonica

## Pull request type

Jira Link: [ON-720](https://storyblok.atlassian.net/browse/ON-720)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

## What is the new behavior?

- 
- 
- 

## Other information

2022-07-28 15:28 UTC, fariacc approved these changes

2022-07-29 08:33 UTC, lisilinhart requested changes
It's a bit weird with the tooltips of the account, 
<img width="187" alt="image" src="https://user-images.githubusercontent.com/11278408/181718627-21363a33-325e-4c00-a4a4-732a920ef3b3.png">

maybe it should be between the help and the account, what do you think?

<img width="204" alt="image" src="https://user-images.githubusercontent.com/11278408/181718837-32c1504f-be2f-4738-b063-2c69adecedbb.png">

2022-08-03 17:25 UTC, fariacc approved these changes

2022-08-04 14:26 UTC, vcpablo approved these changes

2022-08-04 14:31 UTC, fernandacanto approved these changes

2022-08-04 14:48 UTC, merged