fix(str-277)
storyblok/storyblok-design-system pull request #281
Opened 2022-08-08 15:46 UTC by vcpablo

## Pull request type

Jira Link: [STR-277](https://storyblok.atlassian.net/browse/STR-277)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

## What is the new behavior?

- 
- 
- 

## Other information

2022-08-08 16:03 UTC, fariacc approved these changes

2022-08-08 16:04 UTC, fariacc commented on src/components/Menu/index.js
> +    focusWhenOpen: {
I'd just like to suggest changing this to `focusOnOpen` maybe?

2022-08-08 16:56 UTC, fernandacanto requested changes
Hey @vcpablo, please add an example in the storiebook.

2022-08-12 14:26 UTC, vcpablo commented
@fernandacanto, may we open a tech-debt ticket to add a new story in the future.
This is a small fiz of a specific bug that was happening on the Storyblok Editor Page.

2022-08-12 14:28 UTC, fernandacanto approved these changes

2022-08-12 17:39 UTC, merged