fix(str-1272): fix SbSelect to deal properly with created options when multiple
storyblok/storyblok-design-system pull request #295
Opened 2022-08-25 18:45 UTC by vcpablo

This PR fixes the behavior of `multiple` `SbSelect` with `allow-create` prop set to `true`.

## Pull request type

Jira Link: [STR-1272](https://storyblok.atlassian.net/browse/STR-1272)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

The main steps can be found on the ticket.

**It's important to perform a regression tests on all `Multiple Select` scenarios within the application, to make sure everything is working as expected. These are the points:**

**⚠️  For QA (call me so that we can go through the scenarios together)**

_Base Select Occurrences_
<img width="851" alt="image" src="https://user-images.githubusercontent.com/4389464/186743716-4bf28a78-7a16-426a-a1de-babef1707a51.png">

_SbSelect occurrences_
<img width="769" alt="image" src="https://user-images.githubusercontent.com/4389464/186743857-0f12f9a8-6dc3-4163-9e74-10bfd75a7841.png">

## What is the new behavior?

- When the `SbSelect` is `multiple` and has `allow-create` set to `true`, the value will be properly created also when hitting `Enter` key.

## Other information

2022-08-29 15:23 UTC, lorenaramonda approved these changes
Nice improvement @vcpablo ! Works great!

2022-08-29 15:26 UTC, FidalgoMonica approved these changes
It works really nice! Thanks for fixing the bug that I found while I was working on my website :P

2022-08-30 12:07 UTC, thomas-storyblok commented on src/components/Select/Select.vue
>        // doesn't close the list
this comment can now be deleted no?

2022-08-30 16:01 UTC, thomas-storyblok approved these changes
Looks good to me so far :)

2022-08-30 18:32 UTC, emanuelgsouza approved these changes
Nice work man. I just would like to ask you to add some spacing between the last option and the text below. The rest is nice

![image](https://user-images.githubusercontent.com/20342656/187515406-1cc6fa46-416f-4a47-b817-827195d9cfd1.png)

2022-08-31 16:10 UTC, vcpablo commented
> Nice work man. I just would like to ask you to add some spacing between the last option and the text below. The rest is nice
> 
> ![image](https://user-images.githubusercontent.com/20342656/187515406-1cc6fa46-416f-4a47-b817-827195d9cfd1.png)

✅  Done!

2022-09-01 19:11 UTC, sandrodarrieux requested changes
Hey @vcpablo ,

I found this situation:

In Visual Editor -> Workflow, when I type anything and press Enter key, is selecting an item in the list, but is keeping the word that I typed.


https://user-images.githubusercontent.com/58885740/187993752-0b721a1f-8083-4b48-8585-9ae976a99cad.mov

If this is not your fit, please let me know. I evaluated it and in the production version it is not happening.

2022-09-05 15:44 UTC, vcpablo commented
> Hey @vcpablo ,
> 
> I found this situation:
> 
> In Visual Editor -> Workflow, when I type anything and press Enter key, is selecting an item in the list, but is keeping the word that I typed.
> 
>  Gravacao.de.Tela.2022-09-01.as.15.48.04.mov 
> If this is not your fit, please let me know. I evaluated it and in the production version it is not happening.

@sandrodarrieux, there was actually something required for that to work properly.
Already addressed.

Good catch!

2022-09-05 17:40 UTC, sandrodarrieux approved these changes
Nice job, @vcpablo !!

I tested and it's working very well!

2022-09-05 17:52 UTC, merged