fix(work-518): fix pagination number list padding
storyblok/storyblok-design-system pull request #299
Opened 2022-08-31 19:02 UTC by vcpablo

## Pull request type

Jira Link: [WORK-518](https://storyblok.atlassian.net/browse/WORK-518)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

1. Access _Storyblok demo space_
2. Navigate to _Activities_
3. Check the page list on the top bottom
4. Make sure big numbers like 100 or 600 do not cut.
 
**This change will take effect no on _Activities_ page, but all lists with pagination with more than 100 pages available for selection.**

## What is the new behavior?

- Reduce the padding of the pagination list item to fit bigger numbers

## Other information

2022-08-31 19:13 UTC, fernandacanto approved these changes

2022-09-01 07:23 UTC, lisilinhart requested changes
<img width="294" alt="image" src="https://user-images.githubusercontent.com/11278408/187855882-a8661861-077e-400e-8639-412b5bde90d0.png">

Our Storyblok page goes over a 1000 pages, I'm not sure the text should be truncated here or we need a min-width or something

2022-09-06 08:49 UTC, lisilinhart requested changes
<img width="121" alt="image" src="https://user-images.githubusercontent.com/11278408/188591148-0877555e-ccbb-47af-ac54-46d7175a5ddb.png">
It's still cut off 😄

2022-09-07 13:37 UTC, lisilinhart approved these changes

2022-09-07 13:37 UTC, merged