Feat/STR-1264: Add possibility of add icon to SbFormItem
storyblok/storyblok-design-system pull request #300
Opened 2022-08-31 20:58 UTC by fariacc

## Pull request type

Jira Link: [STR-1264](url)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

## What is the new behavior?

- 
- 
- 

## Other information

2022-09-01 07:21 UTC, lisilinhart requested changes
I think the icon needs some spacing like 8px or so:

<img width="261" alt="image" src="https://user-images.githubusercontent.com/11278408/187855570-65204333-f5aa-4d31-985d-1301fad7ddcf.png">


Your PR:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/11278408/187855630-4a35305d-0c72-4b71-8aef-9102958944b6.png">

2022-09-01 14:50 UTC, fariacc commented
> I think the icon needs some spacing like 4-8px or so:
> 
> <img alt="image" width="261" src="https://user-images.githubusercontent.com/11278408/187855570-65204333-f5aa-4d31-985d-1301fad7ddcf.png">
> 
> Your PR:
> 
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/11278408/187855630-4a35305d-0c72-4b71-8aef-9102958944b6.png">

@lisilinhart done ;)

2022-09-01 15:01 UTC, fernandacanto approved these changes
Nice work Carol! 💪🏻

2022-09-02 07:42 UTC, lisilinhart approved these changes

2022-09-02 07:42 UTC, merged