Feat(ON-781): Add user pictogram icon
storyblok/storyblok-design-system pull request #313
Opened 2022-09-21 15:28 UTC by fariacc

## Pull request type

Jira Link: [ON-781](https://storyblok.atlassian.net/browse/ON-781)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

## What is the new behavior?

- 
- 
- 

## Other information

2022-09-23 19:19 UTC, ademarCardoso approved these changes

2022-09-26 09:40 UTC, FidalgoMonica requested changes
Hi Carol, can we maybe remove the unnecessary ids?

![Captura de ecrã 2022-09-26, às 10 39 14](https://user-images.githubusercontent.com/94900845/192244816-dd559cd9-cd23-43a5-b599-f59560ca2968.png)

2022-09-26 18:51 UTC, fariacc commented
> Hi Carol, can we maybe remove the unnecessary ids?
> 
> ![Captura de ecrã 2022-09-26, às 10 39 14](https://user-images.githubusercontent.com/94900845/192244816-dd559cd9-cd23-43a5-b599-f59560ca2968.png)

@FidalgoMonica done, can you review again?

2022-09-27 11:07 UTC, marcosh-ramos approved these changes

2022-09-27 13:10 UTC, merged