fix: remove id from checkboxes
storyblok/storyblok-design-system pull request #334
Opened 2022-11-14 16:47 UTC by lorenaramonda

I removed the id because if we have more than one checkbox in the page loaded by other components instances the IDs are conflicting

## Pull request type

It does not have a ticket related but it's needed for this one:
Jira Link: [FT-6](https://storyblok.atlassian.net/browse/FT-6) 

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

I don't know how you could test this but basically you need to have a richtext field and in the same page another field that uses the same checkbox. In my case it's happening on the feature work for the custom attributes of the link so you can download the main project and switch to the branch related to the issue linked above and then point the DS to this branch. it's the checkbox for the target blank that has been moved inside the multilink fields and so now we can have multiple instances of the checkbox in the page.

For anything let me know.

## What is the new behavior?

- 
- 
- 

## Other information

2022-11-15 14:30 UTC, FidalgoMonica reviewed
I'm not sure that we need to remove the id, since the id is used for accessibility when we click the label, to have the checkbox highlighted.. What I notice it that the "id" is supposed to be a prop. but looking at SbToggle props, I dont see an id... maybe that's what is causing the issue?

2022-11-15 19:26 UTC, lorenaramonda commented
> I'm not sure that we need to remove the id, since the id is used for accessibility when we click the label, to have the checkbox highlighted.. What I notice it that the "id" is supposed to be a prop. but looking at SbToggle props, I dont see an id... maybe that's what is causing the issue?


yes it was i props but i removed it because since it's a props and i need to pass it when it happens in dynamic components i cannot create a unique id for every toggle and so i will have the same id twice or more in the page causing some checkbox to apparently seems to not work as it's selecting only the first one found in the page (or the last), that's why I remove it. but for what i know if you wrap the input inside the label the selection of the checkbox still works without any ID addiction

2022-11-16 08:08 UTC, lisilinhart commented
@lorenaramonda I also think removing the id is problematic in terms of accessibility, because it's necessary with the `label-for` to link labels to inputs. Normally it should be handled on the outside to use unique ids, what field is this problematic in?

2022-11-16 08:39 UTC, lorenaramonda commented
The problem is in this story https://storyfront-git-story-ft-6-link-fields-storyblok-com.vercel.app/#/me/spaces/132139/stories/0/0/219848593 for this task https://github.com/storyblok/storyfront/pull/2738 because we have the exact same toggle in the page that would have the same id and I can't discern from the one in modal and the one in page but it also could happen for other future cases
<img width="1511" alt="Schermata 2022-11-16 alle 09 35 50" src="https://user-images.githubusercontent.com/4409084/202130159-effbd9c7-1e3a-4e20-893c-0f350b03ff33.png">

2022-11-16 08:43 UTC, lisilinhart requested changes
Hey Lori, this causes problem in the app, when using a "custom" built label and reduces the accessibility for those.


https://user-images.githubusercontent.com/11278408/202130646-605aaf75-876b-4ce4-9fee-593a1e2c9606.mov

2022-11-16 08:47 UTC, lorenaramonda commented
Then @lisilinhart  we need to understand how to generate non-repetitive dynamic ID because in my case it's just the same component used in multiple places so the ID is set inside and I cannot handle it

2022-11-16 11:50 UTC, lorenaramonda commented
Ok i can handle with the UUID generated suggested by @lisilinhart so i'm gonna close this PR, thanks!

2022-11-16 11:50 UTC, closed without merging