feat(AR-61): 💄 adds redirection to spaces list logic on header logo click
storyblok/storyblok-design-system pull request #360
Opened 2023-02-01 17:49 UTC by abenmassaoud

## Pull request type

Jira Link: [AR-61](https://storyblok.atlassian.net/browse/AR-61)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

https://user-images.githubusercontent.com/16685155/216122691-2e128fc0-da3f-4a23-9488-6574fa3588ea.mov

## What is the new behavior?

- The component now receives a new **optional** `logoDestinationUrl` prop.

## Other information

This PR is linked to another PR on the storyfront repo.

2023-02-02 18:47 UTC, fernandacanto requested changes
Hi @abenmassaoud, the code is fine, but it's interesting to put an example of use in Sidebar.stories.js. ;)

2023-02-02 22:00 UTC, fariacc commented on src/components/Sidebar/Sidebar.vue
> +        <template v-else>
I don't think it's necessary to wrap these elements inside a template tag if you use `v-if-else` for the image

2023-02-02 22:00 UTC, fariacc approved these changes

2023-02-03 14:53 UTC, fariacc commented on src/components/Sidebar/Sidebar.vue
> +        <template v-else>
Oh I see, thanks for the explanation my friend 🚀

2023-02-03 19:49 UTC, abenmassaoud commented
> Hi @abenmassaoud, the code is fine, but it's interesting to put an example of use in Sidebar.stories.js. ;)

Hi @fernandacanto,
Thank you for the feedback. Indeed an example helps.
I added it [here](https://storyblok-design-system-k8dk8ixk8-storyblok-com.vercel.app/?path=/story/design-system-components-sbsidebar--logo-destination-url) 🙂

2023-02-03 20:06 UTC, merged