Develop
storyblok/storyblok-design-system pull request #87
Opened 2022-01-04 17:18 UTC by thiagosaife

This PR tests the most updated code from develop branch with storyfront's code.

2022-01-04 17:51 UTC, fernandacanto requested changes
I think the merge is great, we just need to check these little points I commented on. 😉

2022-01-04 17:51 UTC, fernandacanto commented on README.md
> -
I believe this part is important and should not remove the README.

2022-01-04 17:51 UTC, fernandacanto commented on src/components/Button/__tests__/Button.spec.js
> +      // expect(wrapper.find('.sb-tooltip').text()).toBe(iconDescription)
Is this comment important?

2022-01-04 17:51 UTC, fernandacanto commented on src/components/Slideover/Slideover.stories.js
> +        },
I believe it's changed causes the Chromatic error.

2022-01-04 17:51 UTC, fernandacanto commented on src/directives/tooltip/__tests__/VTooltip.spec.js
> +// import { mountAttachingComponent } from '../../../utils/tests-utils'
Is this comment important?

2022-01-05 17:32 UTC, thiagosaife commented
@fernandacanto Thanks for pointing those issues. I fixed them on another Pull Request to develop branch. Also fixed the Chromatic errors.

2022-01-05 17:32 UTC, closed without merging